
package com.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T16:04:27.315+08:00
 * Generated source version: 3.4.3
 *
 */
public final class HelloWebService_HelloWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.com/", "HelloWebServiceService");

    private HelloWebService_HelloWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloWebServiceService ss = new HelloWebServiceService(wsdlURL, SERVICE_NAME);
        HelloWebService port = ss.getHelloWebServicePort();

        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_userName = "222";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_userName);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
