package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T15:08:26.904+08:00
 * Generated source version: 3.4.3
 *
 */
@WebServiceClient(name = "HelloWebServiceService",
                  wsdlLocation = "http://localhost:8080/webservice001?wsdl",
                  targetNamespace = "http://service.com/")
public class HelloWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.com/", "HelloWebServiceService");
    public final static QName HelloWebServicePort = new QName("http://service.com/", "HelloWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webservice001?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webservice001?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServicePort")
    public HelloWebService getHelloWebServicePort() {
        return super.getPort(HelloWebServicePort, HelloWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServicePort")
    public HelloWebService getHelloWebServicePort(WebServiceFeature... features) {
        return super.getPort(HelloWebServicePort, HelloWebService.class, features);
    }

}
