package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T15:08:26.878+08:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://service.com/", name = "HelloWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWebService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.com/", className = "com.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.com/", className = "com.service.SayHelloResponse")
    @WebResult(name = "SayHellowRet", targetNamespace = "")
    public java.lang.String sayHello(

        @WebParam(name = "UserName", targetNamespace = "")
        java.lang.String userName
    );
}
